In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([2,2,2])
c = np.array([3,1,1])

matrix = np.column_stack((a,b,c))

In [4]:
matrix

array([[1, 2, 3],
       [2, 2, 1],
       [3, 2, 1]])

In [6]:
A = np.array([[2,3], [4,2],[2,2]])
B = np.array([[4,2], [4,6]])

x = np.dot(A,B)

In [9]:
x

array([[20, 22],
       [24, 20],
       [16, 16]])

In [10]:
matrix_inv = np.linalg.inv(matrix)

In [11]:
matrix_inv

array([[ 3.70074342e-17, -1.00000000e+00,  1.00000000e+00],
       [-2.50000000e-01,  2.00000000e+00, -1.25000000e+00],
       [ 5.00000000e-01, -1.00000000e+00,  5.00000000e-01]])

In [12]:
matrix

array([[1, 2, 3],
       [2, 2, 1],
       [3, 2, 1]])

In [13]:
np.dot(matrix, matrix_inv)

array([[ 1.00000000e+00, -6.66133815e-16,  3.33066907e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.11022302e-16],
       [ 0.00000000e+00, -2.22044605e-16,  1.00000000e+00]])

In [16]:
A = np.array([[2,1,-1],[-3,-1,2], [-2,1,2]])
b = np.array([[8], [-11], [-3]])

A_inv = np.linalg.inv(A)

#solution:
np.dot(A_inv, b)
#But Dangerous because very sensitive, numpy uses LU decomposition instead

array([[ 2.],
       [ 3.],
       [-1.]])

In [17]:
np.linalg.solve(A,b)

array([[ 2.],
       [ 3.],
       [-1.]])